services:
  api:
    image: crive-api:prod
    container_name: crive-api-dev
    platform: linux/amd64
    ports: ["4000:4000"]
    healthcheck:
      test: ["CMD-SHELL","code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4000/healthz || true); [ \"$${code}\" = 200 ] || code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4000/ || true); [ \"$${code}\" = 200 ] || [ \"$${code}\" = 404 ]"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s

  admin:
    image: crive-admin:prod
    container_name: crive-admin-dev
    platform: linux/amd64
    ports: ["3000:3000"]
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://127.0.0.1:3000/ > /dev/null"]
      interval: 10s
      timeout: 2s
      retries: 5
