services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    environment:
      NODE_ENV: development
      PORT: 4000
      HOST: 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./apps/api:/app
      - api_node_modules:/app/node_modules
      - pnpm_store:/pnpm
    command: ["pnpm","-w","--filter","@crive/api","dev"]

  admin:
    image: node:22-alpine
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    volumes:
      - ./apps/admin:/app
      - admin_node_modules:/app/node_modules
      - pnpm_store:/pnpm
    command: ["sh","-lc","corepack enable && pnpm install && pnpm -w --filter @crive/admin dev"]

volumes:
  api_node_modules:
  admin_node_modules:
  pnpm_store:
