name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-build:
    name: Lint • Test • Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm@9 (global)
        run: |
          sudo npm i -g pnpm@9
          which pnpm
          pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint (workspace)
        run: pnpm -r run lint

      - name: Test (workspace)
        run: pnpm -r run test --if-present -- --ci --reporter=dot

      - name: Build (workspace)
        run: pnpm -r run build
