name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'   # tanpa cache
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm -r run typecheck || true
      - run: pnpm -r run build || true
