name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: lint (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, admin, shared]
        node: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: "10.4.0"
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable PNPM cache
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Set workdir env
        run: |
          if [ "${{ matrix.app }}" = "api" ]; then echo "WORKDIR=apps/api" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "admin" ]; then echo "WORKDIR=apps/admin" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "shared" ]; then echo "WORKDIR=packages/shared" >> $GITHUB_ENV; fi

      - name: Prepare node_modules folders
        run: |
          mkdir -p node_modules
          mkdir -p "${{ env.WORKDIR }}/node_modules"

      - name: Cache node_modules
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ env.WORKDIR }}/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-

      # === Stage 5: Install deps (root workspace; sekali saja di matrix 'api') ===
      - name: Install dependencies (workspace)
        if: ${{ hashFiles('pnpm-lock.yaml') != '' && matrix.app == 'api' }}
        run: pnpm install --frozen-lockfile

      # === Stage 6: Lint ===
      - name: Root lint (once, uses root .eslintrc)
        if: ${{ matrix.app == 'api' }}
        run: pnpm exec eslint . --ext .ts,.tsx,.js,.jsx,.cjs,.mjs --max-warnings=0 --no-error-on-unmatched-pattern

      - name: App lint (per workspace)
        working-directory: ${{ env.WORKDIR }}
        run: pnpm exec eslint . --ext .ts,.tsx,.js,.jsx,.cjs,.mjs --max-warnings=0 --no-error-on-unmatched-pattern

  test:
    name: test (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, admin, shared]
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "10.4.0"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Enable PNPM cache
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Set workdir env
        run: |
          if [ "${{ matrix.app }}" = "api" ]; then echo "WORKDIR=apps/api" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "admin" ]; then echo "WORKDIR=apps/admin" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "shared" ]; then echo "WORKDIR=packages/shared" >> $GITHUB_ENV; fi
      - name: Prepare node_modules folders
        run: |
          mkdir -p node_modules
          mkdir -p "${{ env.WORKDIR }}/node_modules"
      - name: Cache node_modules
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ env.WORKDIR }}/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-
      - run: echo "test ${{ matrix.app }} ready"

  build:
    name: build (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, admin, shared]
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "10.4.0"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Enable PNPM cache
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Set workdir env
        run: |
          if [ "${{ matrix.app }}" = "api" ]; then echo "WORKDIR=apps/api" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "admin" ]; then echo "WORKDIR=apps/admin" >> $GITHUB_ENV; fi
          if [ "${{ matrix.app }}" = "shared" ]; then echo "WORKDIR=packages/shared" >> $GITHUB_ENV; fi
      - name: Prepare node_modules folders
        run: |
          mkdir -p node_modules
          mkdir -p "${{ env.WORKDIR }}/node_modules"
      - name: Cache node_modules
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ env.WORKDIR }}/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-${{ matrix.app }}-nodemod-
      - run: echo "build ${{ matrix.app }} ready"

  # Aggregator checks untuk branch protection
  job_lint:
    name: job lint
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ always() }}
    steps:
      - run: |
          echo "needs.lint.result=${{ needs.lint.result }}"
          test "${{ needs.lint.result }}" = "success"

  job_test:
    name: job test
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ always() }}
    steps:
      - run: |
          echo "needs.test.result=${{ needs.test.result }}"
          test "${{ needs.test.result }}" = "success"

  job_build:
    name: job build
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() }}
    steps:
      - run: |
          echo "needs.build.result=${{ needs.build.result }}"
          test "${{ needs.build.result }}" = "success"
