name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [api, admin, shared]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'
          run_install: false
      - name: Install (frozen)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: pnpm -w run lint

  test:
    name: Test (${{ matrix.app }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        app: [api, admin, shared]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'
          run_install: false
      - name: Install (frozen)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Test
        run: pnpm -w run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'
          run_install: false
      - name: Install (frozen)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build
        run: pnpm -w run build
