name: DB Migrations
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        required: true
        type: choice
        options: [stg, prd]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Dry-run with local PG
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/ci_migrate
        run: |
          docker run -d --name ci-pg -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16-alpine
          trap 'docker rm -f ci-pg' EXIT
          pnpm db:migrate:dry

  apply-staging:
    if: ${{ github.event.inputs.env == 'stg' }}
    needs: dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare SSH key (STG)
        run: |
          echo "${{ secrets.STG_SSH_KEY_B64 }}" | base64 -d > id_stg
          chmod 600 id_stg
      - name: Package migrations
        run: tar czf migs.tgz db/migrations db/scripts/migrate.cjs
      - name: Upload & run on STG
        env:
          HOST: ${{ secrets.STG_SSH_HOST }}
          USER: ${{ secrets.STG_SSH_USER }}
          PORT: ${{ secrets.STG_SSH_PORT }}
        run: |
          ssh -i id_stg -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "${PORT:-22}" "$USER@$HOST" 'mkdir -p ~/.crive-migs/work'
          scp -i id_stg -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -P "${PORT:-22}" migs.tgz "$USER@$HOST:~/.crive-migs/work/migs.tgz"
          ssh -i id_stg -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "${PORT:-22}" "$USER@$HOST" '~/.crive-migs/run_migs.sh'

  apply-production:
    if: ${{ github.event.inputs.env == 'prd' }}
    needs: dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare SSH key (PRD)
        run: |
          echo "${{ secrets.PRD_SSH_KEY_B64 }}" | base64 -d > id_prd
          chmod 600 id_prd
      - name: Package migrations
        run: tar czf migs.tgz db/migrations db/scripts/migrate.cjs
      - name: Upload & run on PRD
        env:
          HOST: ${{ secrets.PRD_SSH_HOST }}
          USER: ${{ secrets.PRD_SSH_USER }}
          PORT: ${{ secrets.PRD_SSH_PORT }}
        run: |
          ssh -i id_prd -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "${PORT:-22}" "$USER@$HOST" 'mkdir -p ~/.crive-migs/work'
          scp -i id_prd -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -P "${PORT:-22}" migs.tgz "$USER@$HOST:~/.crive-migs/work/migs.tgz"
          ssh -i id_prd -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "${PORT:-22}" "$USER@$HOST" '~/.crive-migs/run_migs.sh'
