name: DB Migrations

on:
  pull_request:
    paths: [ "db/**" ]
  push:
    branches: [ "main" ]
    paths: [ "db/**" ]
  workflow_dispatch:
    inputs:
      target:
        description: Target environment
        required: true
        type: choice
        options: [stg, prd]
      run_lint:
        description: Also run lint-plan on manual run
        required: false
        type: boolean
        default: false
      run_stg:
        description: Also run apply-stg on manual run
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  lint-plan:
    if: github.event_name == 'pull_request' || github.event.inputs.run_lint == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm -w i --frozen-lockfile=false
      - name: Lint migration files (naming, @down, no DROP)
        run: |
          node -e "const fs=require('fs');const p='db/migrations';
          if(!fs.existsSync(p)){process.exit(0)}
          const bad=[];
          for (const f of fs.readdirSync(p).filter(x=>x.endsWith('.sql'))) {
            if(!/^\d{8,}T?\d{0,6}__.+\.sql$/.test(f)) bad.push('bad name: '+f);
            const t=fs.readFileSync(p+'/'+f,'utf8');
            if(!/^([\s\S]*?)--\s*@down\s*$/m.test(t)) bad.push('missing -- @down: '+f);
            if(/\bDROP\s+(TABLE|COLUMN)\b/i.test(t) && !t.includes('/*allow-drop*/')) bad.push('DROP found (no allow): '+f);
          }
          if(bad.length){console.error(bad.join('\n'));process.exit(1);} "
      - name: Dry-run (plan only)
        run: |
          node -e "
          const fs=require('fs');
          const p='db/migrations';
          if(!fs.existsSync(p)){ console.log('Migrasi terdeteksi: 0'); process.exit(0); }
          const files=fs.readdirSync(p).filter(f=>f.endsWith('.sql')).sort();
          console.log('Migrasi terdeteksi:', files.length);
          files.forEach(f=>console.log('-', f));
          "
      - name: Lint destructiveness
        run: bash scripts/db/lint-migrations.sh
        
  apply-stg:
    if: github.ref == 'refs/heads/main' || github.event.inputs.target == 'stg' || github.event.inputs.run_stg == 'true'
    runs-on: ubuntu-latest
    environment: stg
    env:
      HOST: ${{ secrets.STG_HOST }}
      SSH_KEY_B64: ${{ secrets.STG_SSH_KEY_B64 }}
      DATABASE_URL: ${{ secrets.STG_DATABASE_URL }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STG }}
      DOPPLER_CONFIG: stg
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Install Doppler CLI
        run: curl -sLf https://cli.doppler.com/install.sh | sudo sh

      - name: Install Doppler CLI action
        uses: dopplerhq/cli-action@v3

      - name: Load env from Doppler -> $GITHUB_ENV
        run: |
          set -euo pipefail
          doppler secrets download --no-file --format env \
            --project crive --config "${DOPPLER_CONFIG}" \
            | sed -E 's/^export[[:space:]]+//; s/^;*(.*)$/\1/' \
            >> "$GITHUB_ENV"

      - name: Prepare SSH
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "$SSH_KEY_B64" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Package SQL
        run: |
          set -euo pipefail
          tar -czf migs.tar.gz sql || true
          ls -lah migs.tar.gz || true

      - name: Upload package
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes deploy@"$HOST" 'mkdir -p /deploy/migs'
          scp -o StrictHostKeyChecking=yes migs.tar.gz deploy@"$HOST":/deploy/migs/migs.tar.gz

      - name: Apply SQL (via docker network) — STG
        run: |
          set -euo pipefail
          scp -o StrictHostKeyChecking=yes migs.tar.gz deploy@"$HOST":/tmp/migs.tar.gz
          ssh -o StrictHostKeyChecking=yes deploy@"$HOST" "env DATABASE_URL=\"$DATABASE_URL\" bash -se" <<'REMOTE'
          set -euo pipefail

          rm -rf /deploy/migs/work || true
          mkdir -p /deploy/migs/work
          cd /deploy/migs
          tar -xzf /tmp/migs.tar.gz -C /deploy/migs/work || true

          PG_CONT=$(docker ps --format '{{.Names}}\t{{.Ports}}' | awk '/5432/{print $1; exit}' || true)
          NET=""
          if [ -n "$PG_CONT" ]; then
            NET=$(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{printf "%s " $k}}{{end}}' "$PG_CONT" | awk '{print $1}')
          fi

          run_psql() {
            docker run --rm "$@" -e DATABASE_URL="$DATABASE_URL" \
              -v /deploy/migs/work/sql:/work/sql:ro postgres:alpine sh -lc '
                set -e
                if [ -f /work/sql/up.sql ]; then
                  echo "[apply] up.sql"
                  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /work/sql/up.sql
                else
                  for f in $(ls /work/sql/*.sql 2>/dev/null | sort); do
                    echo "[apply] $f"
                    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
                  done
                fi
              '
          }

          if [ -n "$NET" ] && docker network inspect "$NET" >/dev/null 2>&1; then
            echo "[net] using: --network $NET"
            run_psql --network "$NET"
          elif docker network inspect crive-stack_default >/dev/null 2>&1; then
            echo "[net] using: --network crive-stack_default"
            run_psql --network crive-stack_default
          else
            echo "[net] using: --network host"
            if echo "$DATABASE_URL" | grep -E '://[^@]*@db(:|/)' >/dev/null 2>&1; then
              DATABASE_URL="\$(echo "$DATABASE_URL" | sed 's/@db/@127.0.0.1/')"
            fi
            run_psql --network host
          fi
          REMOTE

      - name: Report summary
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          HOST: ${{ env.HOST }}
          TARGET: ${{ env.TARGET }}
        run: node db/tools/report.mjs

      - name: Audit schema diff
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: bash scripts/db/audit-schema.sh
  
  migrate:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}
      HOST: ${{ github.event.inputs.target == 'stg' && secrets.STG_HOST || secrets.PRD_HOST }}
      SSH_KEY_B64: ${{ github.event.inputs.target == 'stg' && secrets.STG_SSH_KEY_B64 || secrets.PRD_SSH_KEY_B64 }}
      DATABASE_URL: ${{ github.event.inputs.target == 'stg' && secrets.STG_DATABASE_URL || secrets.PRD_DATABASE_URL }}
      DOPPLER_TOKEN: ${{ github.event.inputs.target == 'stg' && secrets.DOPPLER_TOKEN_STG || secrets.DOPPLER_TOKEN_PRD }}
      DOPPLER_CONFIG: ${{ github.event.inputs.target == 'stg' && 'stg' || 'prd' }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Install Doppler CLI
        run: curl -sLf https://cli.doppler.com/install.sh | sudo sh

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Load env from Doppler → $GITHUB_ENV
        run: |
          set -euo pipefail
          doppler secrets download --no-file --format env \
            --project crive --config "${DOPPLER_CONFIG}" \
          | sed -E 's/^export[[:space:]]+//; s/="(.*)"$/=\1/' \
          >> "$GITHUB_ENV"

      - name: Prepare SSH
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "$SSH_KEY_B64" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Package SQL
        run: |
          set -euo pipefail
          tar -czf migs.tar.gz sql || true
          ls -lah migs.tar.gz

      - name: Upload package
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes deploy@"$HOST" 'mkdir -p /deploy/migs'
          scp -o StrictHostKeyChecking=yes migs.tar.gz deploy@"$HOST":/deploy/migs/migs.tar.gz

      - name: Snapshot before migrate (PRD only)
        if: env.TARGET == 'prd'
        env:
          BACKUP_PASSPHRASE: ${{ secrets.BACKUP_PASSPHRASE }}
        run: |
          # runner: jangan -u (hindari unbound), tetap pipefail
          set -eo pipefail
          BP="${BACKUP_PASSPHRASE-}"

          ssh -o StrictHostKeyChecking=yes deploy@"$HOST" \
            "env DATABASE_URL=\"$DATABASE_URL\" BACKUP_PASSPHRASE=\"$BP\" bash -se" <<'REMOTE'
          set -euo pipefail
          : "${DATABASE_URL:?missing}"

          # --- passphrase fallback (tetap bisa snapshot walau secret kosong)
          if [ -z "${BACKUP_PASSPHRASE:-}" ]; then
            echo "::warning title=BACKUP_PASSPHRASE missing::Using ephemeral passphrase for snapshot"
            BACKUP_PASSPHRASE="$(openssl rand -hex 16)"
          fi

          mkdir -p /deploy/backups
          STAMP="$(date +'%Y%m%d-%H%M')"
          OUT="/deploy/backups/crive-${STAMP}.dump"

          # --- deteksi network Postgres (agar host 'db' ter-resolve)
          PG_CONT="$(docker ps --format '{{.Names}}\t{{.Ports}}' | awk '/5432/{print $1; exit}' || true)"
          NET=""
          if [ -n "$PG_CONT" ]; then
            NET="$(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{printf "%s " $k}}{{end}}' "$PG_CONT" | awk '{print $1}')"
          fi

          SNAP_OK=0
          if [ -n "$NET" ] && docker network inspect "$NET" >/dev/null 2>&1; then
            echo "[snapshot] using docker network: $NET"
            docker run --rm --network "$NET" \
              -e DATABASE_URL="$DATABASE_URL" \
              -v /deploy/backups:/backup \
              postgres:alpine sh -lc 'pg_dump --no-owner --format=custom "$DATABASE_URL" -f /backup/out.dump'
            mv "/deploy/backups/out.dump" "$OUT"
            SNAP_OK=1
          elif docker network inspect crive-stack_default >/dev/null 2>&1; then
            echo "[snapshot] using docker network: crive-stack_default"
            docker run --rm --network crive-stack_default \
              -e DATABASE_URL="$DATABASE_URL" \
              -v /deploy/backups:/backup \
              postgres:alpine sh -lc 'pg_dump --no-owner --format=custom "$DATABASE_URL" -f /backup/out.dump'
            mv "/deploy/backups/out.dump" "$OUT"
            SNAP_OK=1
          else
            echo "[snapshot] no docker network; trying host"
            URL="$DATABASE_URL"
            if echo "$URL" | grep -E '://[^@]*@db(:|/)' >/dev/null 2>&1; then
              URL="$(echo "$URL" | sed 's/@db/@127.0.0.1/')"
            fi
            if pg_dump --no-owner --format=custom "$URL" -f "$OUT"; then
              SNAP_OK=1
            fi
          fi

          if [ "$SNAP_OK" -ne 1 ]; then
            echo "::error title=Snapshot failed::Unable to dump database on any network mode"
            exit 1
          fi

          gpg --batch --yes --passphrase "$BACKUP_PASSPHRASE" -c "$OUT"
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "$OUT.gpg" > "$OUT.gpg.sha256"
          else
            shasum -a 256 "$OUT.gpg" > "$OUT.gpg.sha256"
          fi
          rm -f "$OUT"
          echo "Snapshot OK: $OUT.gpg"
          REMOTE

      - name: Apply SQL (via docker network)
        run: |
          set -euo pipefail
          
          RAW_DB='${{ env.DATABASE_URL }}'
          RAW_DB=${RAW_DB#\"}; RAW_DB=${RAW_DB%\"}
          DB_URL="${RAW_DB//sslmode=require/sslmode=disable}"

          DB_URL="${DATABASE_URL//sslmode=require/sslmode=disable}"
          DB_URL_ESC=$(printf "%s" "$DB_URL" | sed "s/'/'\"'\"'/g")

          scp -o StrictHostKeyChecking=yes migs.tar.gz deploy@"$HOST":/tmp/migs.tar.gz

          # kirim DB_URL ke sesi remote lewat prefix env pada perintah
          ssh -o StrictHostKeyChecking=yes deploy@"$HOST" "DATABASE_URL='$DB_URL_ESC' bash -se" <<'REMOTE'
          set -euo pipefail
          mkdir -p /deploy/migs && rm -rf /deploy/migs/work || true
          cd /deploy/migs
          tar -xzf /tmp/migs.tar.gz

          PG_CONT=$(docker ps --format '{{.Names}}\t{{.Ports}}' | awk '/5432/{print $1; exit}')
          NET=$(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{printf "%s" $k}}{{end}}' "$PG_CONT")

          docker run --rm --network "$NET" -e DATABASE_URL="$DATABASE_URL" \
            -v "$PWD/sql:/work/sql:ro" postgres:16-alpine sh -lc '
              set -e
              echo "[preflight] select 1"; psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "select 1";
              if ls /work/sql/up/*.sql >/dev/null 2>&1; then
                for f in $(ls -1 /work/sql/up/*.sql | sort); do
                  echo "[apply] $f"; psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f";
                done
              elif [ -f /work/sql/up.sql ]; then
                echo "[apply] /work/sql/up.sql"; psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /work/sql/up.sql;
              else
                echo "[apply] tidak ada sql/up";
              fi
            '
          REMOTE

      - name: Report summary
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          HOST: ${{ env.HOST }}
          TARGET: ${{ env.TARGET }}
        run: node db/tools/report.mjs

       - name: Audit schema diff
         env:
           DATABASE_URL: ${{ env.DATABASE_URL }}
         run: bash scripts/db/audit-schema.sh