name: DB Migrations
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to apply (stg|prd)"
        required: true
        default: "stg"

jobs:
  dry-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: ci_migrate
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U pguser -d ci_migrate"
          --health-interval=5s --health-timeout=5s --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Set DATABASE_URL to CI Postgres
        run: echo "DATABASE_URL=postgres://pguser:pgpass@127.0.0.1:5432/ci_migrate" >> $GITHUB_ENV
      - name: Dry-run migrations
        run: pnpm db:migrate:dry

  apply-staging:
    needs: dry-run
    if: ${{ github.event.inputs.env == 'stg' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Set DATABASE_URL (stg)
        run: echo "DATABASE_URL=${{ secrets.STG_DATABASE_URL }}" >> $GITHUB_ENV
      - name: Migrate Up (staging)
        run: pnpm db:migrate:up

  apply-production:
    needs: dry-run
    if: ${{ github.event.inputs.env == 'prd' }}
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: https://api.crive.app/healthz
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Set DATABASE_URL (prd)
        run: echo "DATABASE_URL=${{ secrets.PRD_DATABASE_URL }}" >> $GITHUB_ENV
      - name: Migrate Up (production)
        run: pnpm db:migrate:up
