name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: none

jobs:
  deploy-stg:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v4
      - run: echo "STG skip (no staging server)"

deploy-prd:
  runs-on: ubuntu-latest
  environment: prd
  needs: [deploy-stg]
  steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRD_SSH_KEY }}

    - name: Deploy PRD via SSH
      env:
        HOST: 209.97.172.49
      run: |
        ssh -o StrictHostKeyChecking=no root@$HOST <<'SH'
        set -a; source /etc/doppler/prod.env; set +a
        cd /deploy
        doppler run --project crive --config prd -- docker compose up -d --remove-orphans
        SH
