name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-stg:
    name: deploy-stg
    runs-on: ubuntu-latest
    steps:
      - name: No-op (stg)
        run: echo "stg ok"
  deploy-prd:
    name: deploy-prd
    runs-on: ubuntu-latest
    needs: deploy-stg
    environment: prd
    steps:
      - name: Validate required secrets (prd)
        env:
          PRD_SSH_HOST: ${{ secrets.PRD_SSH_HOST }}
          PRD_SSH_USER: ${{ secrets.PRD_SSH_USER }}
          PRD_SSH_KEY: ${{ secrets.PRD_SSH_KEY }}
          PRD_SSH_KEY_B64: ${{ secrets.PRD_SSH_KEY_B64 }}
        run: |
          set -euo pipefail
          [[ -n "${PRD_SSH_HOST:-}" ]] || { echo "Missing PRD_SSH_HOST"; exit 1; }
          [[ -n "${PRD_SSH_USER:-}" ]] || { echo "Missing PRD_SSH_USER"; exit 1; }
          if [[ -z "${PRD_SSH_KEY:-}" && -z "${PRD_SSH_KEY_B64:-}" ]]; then
            echo "Missing PRD_SSH_KEY or PRD_SSH_KEY_B64"; exit 1
          fi
          echo "Secrets present"
      - name: Prepare SSH key (prd)
        env:
          PRD_SSH_HOST: ${{ secrets.PRD_SSH_HOST }}
          PRD_SSH_USER: ${{ secrets.PRD_SSH_USER }}
          PRD_SSH_PORT: ${{ secrets.PRD_SSH_PORT }}
          PRD_SSH_KEY: ${{ secrets.PRD_SSH_KEY }}
          PRD_SSH_KEY_B64: ${{ secrets.PRD_SSH_KEY_B64 }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          if [[ -n "${PRD_SSH_KEY_B64:-}" ]]; then
            echo "$PRD_SSH_KEY_B64" | base64 -d > ~/.ssh/id_ed25519_prd_ci
          else
            echo "$PRD_SSH_KEY" > ~/.ssh/id_ed25519_prd_ci
          fi
          sed -i 's/\r$//' ~/.ssh/id_ed25519_prd_ci || true
          chmod 600 ~/.ssh/id_ed25519_prd_ci
          {
            echo "Host prdhost"
            echo "  HostName ${PRD_SSH_HOST}"
            echo "  User ${PRD_SSH_USER}"
            echo "  Port ${PRD_SSH_PORT:-22}"
            echo "  IdentityFile ~/.ssh/id_ed25519_prd_ci"
            echo "  StrictHostKeyChecking yes"
            echo "  BatchMode yes"
          } >> ~/.ssh/config
          chmod 600 ~/.ssh/config
      - name: Add known_hosts (prd)
        env:
          PRD_SSH_HOST: ${{ secrets.PRD_SSH_HOST }}
          PRD_SSH_PORT: ${{ secrets.PRD_SSH_PORT }}
        run: |
          set -euo pipefail
          ssh-keyscan -T 5 -p "${PRD_SSH_PORT:-22}" "${PRD_SSH_HOST}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH preflight (whoami & groups)
        run: |
          set -x
          ssh prdhost 'whoami && id -nG && echo PRECHECK_OK'
      - name: Deploy (docker compose)
        run: |
          set -euo pipefail
          ssh prdhost 'bash -s' <<'EOS'
          set -euo pipefail

          # 1) Ambil secrets dari Doppler (sebutkan PROJECT + CONFIG)
          GHCR_USER="$(doppler secrets get GHCR_USERNAME --project crive --config prd --plain)"
          GHCR_PASS="$(doppler secrets get GHCR_TOKEN    --project crive --config prd --plain)"
          [ -n "$GHCR_USER" ] && [ -n "$GHCR_PASS" ] || { echo "GHCR secrets missing"; exit 1; }

          # 2) Login GHCR (non-TTY)
          echo "$GHCR_PASS" | docker login ghcr.io -u "$GHCR_USER" --password-stdin && echo "Login Succeeded"

          # 3) Deploy
          cd /deploy
          docker compose pull
          docker compose up -d
          docker compose ps

          # 4) Health check (wajib 200/200)
          API="$(curl -s -o /dev/null -w "%{http_code}" https://api.crive.app/healthz)"
          WEB="$(curl -s -o /dev/null -w "%{http_code}" https://crive.app/healthz)"
          echo "api:$API"; echo "web:$WEB"
          test "$API" = "200" && test "$WEB" = "200"
          EOS
