name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: none

jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v4
      - run: echo "STG skip (no staging server)"

  deploy-prd:
    runs-on: ubuntu-latest
    environment: prd
    needs: deploy-stg
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH (decode base64)
          run: |
          set -euo pipefail
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          echo "${{ secrets.PRD_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          sed -i 's/\r$//' ~/.ssh/id_ed25519 || true
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -lf ~/.ssh/id_ed25519 >/dev/null
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
          deploy@209.97.172.49 'echo SSH_OK && whoami'

      - name: Deploy PRD via SSH
        env:
          HOST: 209.97.172.49
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o IdentitiesOnly=yes deploy@$HOST <<'SH'
          set -e
          set -a; source /etc/doppler/prd.env; set +a
          cd /deploy
          doppler run --project crive --config prd -- docker compose up -d --remove-orphans
          SH
