name: deps-audit
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: mkdir -p reports

      - name: Audit (prod)
        run: pnpm audit --prod
        continue-on-error: true   # non-gating

      - name: SBOM
        run: pnpm dlx @cyclonedx/cyclonedx-npm --output-format json --output-file reports/sbom.json
        continue-on-error: true

      - name: Licenses
        run: pnpm -r licenses list --prod | tee reports/licenses.txt
        continue-on-error: true

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deps-reports
          path: reports
