name: deps-audit

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.2
          run_install: false
      - run: node -v && pnpm -v
      # ↓ ganti sesuai kebutuhanmu (sementara aman tidak error)
      - name: Install & audit
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm -r run deps:audit || true
      - run: corepack enable
      - run: corepack prepare pnpm@10.14.2 --activate
      - run: node -v && pnpm -v
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Install & audit
        run: pnpm audit || true
