name: deps-audit

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.2
          run_install: false
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Audit (prod)
        run: pnpm audit --prod || true   # tetap hijau; jadikan alert saja di report

      - name: SBOM
        run: npx --yes @cyclonedx/cyclonedx-npm --output-format json --output-file reports/sbom.json
        continue-on-error: true

      - name: Licenses
        run: pnpm -r licenses list --prod || true
        continue-on-error: true
