name: deps-audit

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.2
          run_install: false
      - name: Ensure pnpm in PATH
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm missing, installing via npm..."
            npm i -g pnpm@10.14.2
          fi
          pnpm -v
          node -v
        with:
          node-version: '24.x'
      - run: corepack enable
      - run: corepack prepare pnpm@10.14.2 --activate
      - run: node -v && pnpm -v
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Install & audit
        run: pnpm audit || true
