name: deps-audit

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

  workflow_dispatch:    # manual dulu; tidak blocking PR>>>>>>> main

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.2
          run_install: false
      - run: pnpm -v && node -v
      - run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Audit (prod)
        run: pnpm run deps:audit:prod

      - name: SBOM
        run: pnpm run deps:sbom
        continue-on-error: true
        run: pnpm audit --prod || true         # non-gating: tidak memecah build
     
     - name: SBOM
        run: pnpm dlx cyclonedx-npm --output-format json --output-file reports/sbom.json || true

      - name: Licenses
        run: pnpm -r licenses list --prod || true
