name: deps-audit
on:
  pull_request:
    branches: [ main ]
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: latest }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install (frozen, ignore scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Audit (prod only)
        run: pnpm run deps:audit:prod
      - name: SBOM (CycloneDX)
        run: pnpm run deps:sbom
      - name: Licenses
        run: pnpm run deps:licenses
