name: deps-audit

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Audit (prod)
        run: pnpm run deps:audit:prod
      - name: SBOM
        run: pnpm dlx @cyclonedx/cyclonedx-npm --output-format json --output-file reports/sbom.json
      - name: Licenses (non-gating)
        run: pnpm -r licenses list --prod || true
