name: Hardening/12 licenses
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Pass stub
        run: echo "licenses check stub: OK"
