name: Hardening/12 licenses

on:
  push:
    branches: [hardening/12-licenses]
  pull_request:
    branches: [hardening/12-licenses]
=======
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: hardening-12-licenses-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

concurrency:
  group: hardening-12-licenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack & activate pnpm (from packageManager)
        run: |
          set -euo pipefail
          corepack enable
          VER=$(node -p "(()=>{try{const pm=(require('./package.json').packageManager||'pnpm@10.14.0');return pm.split('@')[1]||'10.14.0'}catch(e){return '10.14.0'}})()")
          echo "Using pnpm ${VER}"
          corepack prepare pnpm@${VER} --activate
          pnpm -v
          node-version: '24.x'
          
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_path: package.json
          version: 10.14.0
          run_install: false
      - run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install deps (non-frozen for this workflow)
        run: pnpm install --no-frozen-lockfile

      - name: Generate license report
        run: |
          set -euo pipefail
          pnpm dlx -y license-checker-rseidelsohn --summary --production --json > license-report.json
          # jaga-jaga kalau tool tidak output apa-apa:
          test -s license-report.json || echo "{}" > license-report.json
          ls -l license-report.json

      - name: Upload license artifact
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: license-report.json
          name: licenses-report
          path: licenses.json