name: hardening/12: SBOM (CycloneDX)
on:
  push: { branches: [hardening/12-licenses] }
  pull_request: { branches: [hardening/12-licenses] }
permissions:
  contents: read
  id-token: write
  attestations: write
concurrency: { group: sbom-${{ github.ref }}, cancel-in-progress: true }
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Enable Corepack & activate pnpm
        run: |
          set -euo pipefail
          corepack enable
          VER=$(node -p "(()=>{try{const pm=(require('./package.json').packageManager||'pnpm@10.14.0');return pm.split('@')[1]||'10.14.0'}catch(e){return '10.14.0'}})()")
          corepack prepare pnpm@${VER} --activate
          pnpm -v
      - name: Install deps (frozen, no scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Generate CycloneDX SBOM (JSON)
        run: |
          set -euo pipefail
          pnpm dlx -y @cyclonedx/cyclonedx-npm@4 --json --output-file sbom.json
          test -s sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom.json }
      - name: Attest SBOM (SLSA provenance)
        uses: actions/attest-build-provenance@v1
        with: { subject-path: sbom.json }
