name: Hardening/12 licenses
on:
  push: { branches: [hardening/12-licenses] }
  pull_request: { branches: [hardening/12-licenses] }

permissions: { contents: read }
concurrency:
  group: hardening-12-licenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack & activate pnpm (from packageManager)
        run: |
          set -euo pipefail
          corepack enable
          VER=$(node -p "(()=>{try{const pm=(require('./package.json').packageManager||'pnpm@10.14.0');return pm.split('@')[1]||'10.14.0'}catch(e){return '10.14.0'}})()")
          echo "Using pnpm ${VER}"
          corepack prepare pnpm@${VER} --activate
          pnpm -v

      - name: Install deps (non-frozen)
        run: pnpm install --no-frozen-lockfile

      - name: Generate license report (always create file)
        run: |
          set -euo pipefail
          mkdir -p reports
          pnpm dlx -y license-checker-rseidelsohn --summary --production --json \
            > reports/license-report.json || echo '{}' > reports/license-report.json
          test -s reports/license-report.json || echo '{}' > reports/license-report.json
          ls -lh reports/license-report.json
          head -c 300 reports/license-report.json || true

      - name: Upload license artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: reports/license-report.json
          if-no-files-found: warn
          retention-days: 7
