name: Hardening/12 licenses

on:
  push:
    branches: [hardening/12-licenses]
  pull_request:
    branches: [hardening/12-licenses, main]

permissions:
  contents: read

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack & activate pnpm (from packageManager)
        run: |
          set -euo pipefail
          corepack enable
          corepack prepare pnpm@10.14.2 --activate
          pnpm -v
      - name: Install deps (non-frozen untuk tool lisensi)
        run: pnpm install --no-frozen-lockfile
      - name: Generate license report
        run: |
          set -euo pipefail
          pnpm dlx -y license-checker-rseidelsohn --summary --production --json > license-report.json
          test -s license-report.json || echo '{"summary":{}}' > license-report.json
      - name: Upload license artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-report
          path: license-report.json
          if-no-files-found: warn
