name: Hardening/12 licenses
on:
  pull_request:
  push:
    branches: [main, hardening/**, feat/**]
permissions:
  contents: read
jobs:
  licenses:
    runs-on: ubuntu-latest
    continue-on-error: true   # <- job dianggap sukses walau ada step gagal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Setup pnpm (robust)
        run: |
          if command -v corepack >/dev/null 2>&1; then
            corepack enable || true
            corepack use pnpm@10.14.0 || npm i -g pnpm@10.14.0
          else
            npm i -g pnpm@10.14.0
          fi
          pnpm -v

      - name: Install (frozen, ignore scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Generate license report (JSON)
        run: |
          pnpm dlx license-checker-rseidelsohn@3.4.2 license-checker \
            --json --production --relativeLicensePath --excludePrivatePackages \
            > license-report.json

      - name: Upload license-report.json
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: license-report.json
          retention-days: 14

      # Hanya ringkas — tidak ada gate/fail
      - name: License summary (non-blocking)
        if: always()
        run: |
          echo "### License Report" >> $GITHUB_STEP_SUMMARY
          echo "- Artifact: \`license-report.json\`" >> $GITHUB_STEP_SUMMARY
          jq -r 'to_entries[] | [.key, .value.licenses] | @tsv' license-report.json | head -n 200 >> $GITHUB_STEP_SUMMARY || true
