name: hardening/12: lockfile-guard

on:
  pull_request:
    branches: [hardening/12-licenses]

permissions: { contents: read }

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Fail if lockfile changed without allowed labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          base_sha=${{ github.event.pull_request.base.sha }}
          git diff --name-only "$base_sha"...HEAD > changed.txt
          if grep -q '^pnpm-lock.yaml$' changed.txt; then
            echo "Lockfile changed."
            labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | tr '[:upper:]' '[:lower:]' || true)
            echo "PR labels: $labels"
            if echo "$labels" | grep -Eq '(deps|renovate|dependabot)'; then
              echo "Allowed label present. OK."
            else
              echo "::error::pnpm-lock.yaml changed but PR lacks label deps/renovate/dependabot."
              exit 1
            fi
          else
            echo "No lockfile changes. OK."
          fi
