name: lockfile-discipline
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  contents: read
  pull-requests: read
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pnpm-lock.yaml changed
        id: diff
        uses: actions/github-script@v7
        with:
          script: |
            const files = await github.paginate(
              github.rest.pulls.listFiles, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                per_page: 100
              }
            );
            const changed = files.some(f => f.filename.endsWith('pnpm-lock.yaml'));
            core.setOutput('changed', String(changed));
      - name: Enforce label if lockfile changed
        if: steps.diff.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(l => l.name);
            const ok = labels.includes('deps') || labels.includes('renovate');
            if (!ok) {
              core.setFailed('pnpm-lock.yaml berubah. Tambahkan label `deps` atau `renovate` pada PR ini.');
            }
