name: hardening/12: lockfile-guard

on:
  pull_request:
    branches: [hardening/12-licenses]
permissions: { contents: read, pull-requests: read }
concurrency: { group: lockfile-${{ github.ref }}, cancel-in-progress: true }

on:
  pull_request:
    branches: [hardening/12-licenses]

permissions: { contents: read }

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Validate lockfile changes
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.event.pull_request.head.sha }}
          LABELS: ${{ toJSON(github.event.pull_request.labels) }}
          ACTOR: ${{ github.actor }}
        run: |
          set -euo pipefail
          CHANGED=$(git diff --name-only "$BASE".."$HEAD" | grep -E '(^|/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock)$' || true)
          echo "Changed lockfiles:"
          echo "${CHANGED:-<none>}"
          allowed_actor=$(printf '%s' "$ACTOR" | grep -Eiq 'dependabot|renovate' && echo yes || echo no)
          has_label=$(printf '%s' "$LABELS" | jq -r 'map(.name)|index("deps")|if .==null then "no" else "yes" end')
          if [ -n "$CHANGED" ] && [ "$allowed_actor" = "no" ] && [ "$has_label" = "no" ]; then
            echo "::error::Lockfile changed but PR lacks label 'deps' (or actor not dependabot/renovate)."
            exit 1
          fi
          echo "OK"

      - name: Fail if lockfile changed without allowed labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          base_sha=${{ github.event.pull_request.base.sha }}
          git diff --name-only "$base_sha"...HEAD > changed.txt
          if grep -q '^pnpm-lock.yaml$' changed.txt; then
            echo "Lockfile changed."
            labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | tr '[:upper:]' '[:lower:]' || true)
            echo "PR labels: $labels"
            if echo "$labels" | grep -Eq '(deps|renovate|dependabot)'; then
              echo "Allowed label present. OK."
            else
              echo "::error::pnpm-lock.yaml changed but PR lacks label deps/renovate/dependabot."
              exit 1
            fi
          else
            echo "No lockfile changes. OK."
          fi
