name: OSV scan

on:
  pull_request:
    branches: [hardening/12-licenses, main]
  push:
    branches: [hardening/12-licenses]

permissions:
  contents: read

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google/osv-scanner-action@v1
        with:
          scan-args: >-
            --lockfile=pnpm-lock.yaml
            --output=osv.json
      - uses: actions/upload-artifact@v4
        with:
          name: osv
          path: osv.json
