name: Provenance
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  attestations: write

concurrency:
  group: provenance-${{ github.ref }}
  cancel-in-progress: true

jobs:
  slsa:
    name: Build provenance (SLSA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      # SBOM tanpa pnpm/action; gunakan npx agar bebas konflik versi
      - name: Generate SBOMs (CycloneDX via npx)
        run: |
          set -euo pipefail
          mkdir -p artifacts/sbom
          gen() { d="$1"; [ -d "$d" ] || return 0; (
            cd "$d"
            name=$(node -p "require('./package.json').name || require('path').basename(process.cwd())")
            npx -y @cyclonedx/cyclonedx-npm --output-format json --spec-version 1.5 --omit dev \
              --output-file "../artifacts/sbom/sbom-${name}.json"
          ); }
          gen apps/api
          gen apps/admin
          gen packages/shared
        continue-on-error: true

      - name: Upload SBOM artifacts
        if: ${{ always() && hashFiles('artifacts/sbom/*.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: provenance-sbom-${{ github.sha }}
          path: artifacts/sbom/*.json
          retention-days: 30

      - name: Attest build provenance
        if: ${{ hashFiles('artifacts/sbom/*.json') != '' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifacts/sbom/*.json
        continue-on-error: true
