name: Registry policy
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan non-digested images
        id: scan
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifacts
          # Cari image yang masih pakai tag (bukan digest)
          rg -n -P --glob '!**/node_modules/**' \
            -e '^\s*FROM\s+\S+:(?!.*@sha256:)\S+' \
            -e '^\s*image:\s+\S+:(?!.*@sha256:)\S+' \
            . | tee artifacts/registry-violations.txt || true

          if [ -s artifacts/registry-violations.txt ]; then
            echo "violations=true" >> "$GITHUB_OUTPUT"
            exit 2
          fi

      - name: Upload violations (only when failed)
        if: failure() && steps.scan.outputs.violations == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: registry-violations-${{ github.sha }}
          path: artifacts/registry-violations.txt
          if-no-files-found: error
          retention-days: 7
