name: Reproducible build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  repro:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install (frozen + no scripts)
        run: npx -y pnpm@10.14.2 install --frozen-lockfile --ignore-scripts

      - name: Build (skip paket tanpa script)
        run: npx -y pnpm@10.14.2 -r --if-present run build

      - name: Ensure reproducible (no repo changes)
        shell: bash
        run: |
          set -e
          mkdir -p artifacts/repro
          git status --porcelain=v1 > artifacts/repro/status.txt || true
          if ! git diff --quiet; then
            git --no-pager diff > artifacts/repro/diff.patch || true
            echo "::error::Build produced repo changes (not reproducible). See artifacts/repro/diff.patch"
            exit 1
          fi
          node -v                                    > artifacts/repro/env.txt
          npx -y pnpm@10.14.2 -v                    >> artifacts/repro/env.txt
          npx -y pnpm@10.14.2 list -r --depth -1     > artifacts/repro/tree.txt || true

      - name: Upload repro artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repro-${{ github.sha }}
          path: artifacts/repro/*
          if-no-files-found: warn
