name: Reproducible build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  repro:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node 24.x (cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'

      # 1) pnpm/action-setup (tidak mematikan job bila gagal)
      - name: Setup PNPM via action
        uses: pnpm/action-setup@v4
        continue-on-error: true
        with:
          version: 10.14.2
          run_install: false

      # 2) Fallback corepack (tidak mematikan job bila gagal)
      - name: Fallback via corepack
        shell: bash
        continue-on-error: true
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            corepack enable
            corepack prepare pnpm@10.14.2 --activate
          fi

      # 3) Fallback terakhir: global npm
      - name: Final fallback via npm -g
        shell: bash
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            npm i -g pnpm@10.14.2
          fi
          echo "PNPM=$(pnpm --version)"
          which pnpm

      - name: Install (frozen + no scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build (skip paket tanpa script)
        run: pnpm -r --if-present run build

      - name: Ensure reproducible (no repo changes)
        shell: bash
        run: |
          set -e
          mkdir -p artifacts/repro
          git status --porcelain=v1 > artifacts/repro/status.txt || true
          if ! git diff --quiet; then
            git --no-pager diff > artifacts/repro/diff.patch || true
            echo "::error::Build produced repo changes (not reproducible). See artifacts/repro/diff.patch"
            exit 1
          fi
          node -v   > artifacts/repro/env.txt
          pnpm -v  >> artifacts/repro/env.txt
          pnpm list -r --depth -1 > artifacts/repro/tree.txt || true

      - name: Upload repro artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repro-${{ github.sha }}
          path: artifacts/repro/*
          if-no-files-found: warn
