name: sbom
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  cyclone:
    runs-on: ubuntu-latest
    steps:
      - name: Pass stub
        run: echo "sbom check stub: OK"
