name: sbom
on:
  pull_request:
  push:
    branches: [main, hardening/**, feat/**]
permissions:
  contents: read
jobs:
  cyclone:
    runs-on: ubuntu-latest
    continue-on-error: true   # <- job dianggap sukses walau ada step gagal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Setup pnpm (robust)
        run: |
          if command -v corepack >/dev/null 2>&1; then
            corepack enable || true
            corepack use pnpm@10.14.0 || npm i -g pnpm@10.14.0
          else
            npm i -g pnpm@10.14.0
          fi
          pnpm -v

      - name: Install (frozen, ignore scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Generate CycloneDX SBOM (JSON)
        run: |
          pnpm dlx @cyclonedx/cyclonedx-npm@4.1.0 \
            --output-format json \
            --output-path ./sbom-cyclonedx.json || echo '{}' > sbom-cyclonedx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom-cyclonedx.json
          retention-days: 14

      - name: SBOM summary (non-blocking)
        if: always()
        run: |
          echo "### SBOM (CycloneDX)" >> $GITHUB_STEP_SUMMARY
          echo "- Artifact: \`sbom-cyclonedx.json\`" >> $GITHUB_STEP_SUMMARY
          jq -r '.components? | length // 0 | tostring' sbom-cyclonedx.json | xargs -I{} echo "- Components: {}" >> $GITHUB_STEP_SUMMARY || true
