name: Secret Scan (gitleaks)

on:
  push:
    branches: [ main, develop, "feature/**", "chore/**" ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Tanpa 'with: args', biarkan default action yang handle
