name: Secret Scan (gitleaks)

on:
  pull_request:
  push:
    branches: [ main, develop, "feature/**", "chore/**" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run gitleaks (workspace only)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --config=.gitleaks.toml \
            --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
