name: slsa-provenance
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
permissions:
  id-token: write
  contents: write
jobs:
  provenance:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ github.event.workflow_run.id }}"
